eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8081
spring:
  application:
    name: customer
vehicle:
  application:
    name: vehicle
  service: /vehicle/


---
spring:
  profiles: docker
  
eureka:
  instance:
    prefer-ip-address: true
    hostname: EC2Co-EcsEl-Y61HWAZ0CMB8-1226310100.us-east-1.elb.amazonaws.com
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}