eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
spring:
  application:
    name: gateway
zuul:
  routes:
    customer:
      path: customer/**
      service-id: customer
    vehicle:
      path: vehicle/**
      service-id: vehicle

---
spring:
  profiles: docker
  
eureka:
  instance:
    hostname: EC2Co-EcsEl-Y61HWAZ0CMB8-1226310100.us-east-1.elb.amazonaws.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}
      
