eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8082
spring:
  application:
    name: vehicle
    
---
spring:
  profiles: docker
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}
