version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - cd customer
      - ./mvnw test -Deureka.client.enabled=false  -B
      - echo Build completed on `date`
      - ./mvnw package -Deureka.client.enabled=false -DskiptTests  -B
      - docker build -t customer .
  post_build:
    commands:
      - eval `aws ecr get-login --no-include-email --region us-east-1`
      - docker tag customer:latest 722103257780.dkr.ecr.us-east-1.amazonaws.com/alten-vehicle/customer:latest
      - docker push 722103257780.dkr.ecr.us-east-1.amazonaws.com/alten-vehicle/customer:latest